name: CI

on:
  push:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - unlocked

jobs:
  run-tests:
    name: Run tests
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      # Setup .npmrc file to publish to GitHub Packages
      - uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          registry-url: 'https://npm.pkg.github.com'
          # Defaults to the user or organization that owns the workflow file
          scope: '@pavelkeyzik'
      - run: npm ci
      - run: npm test