name: Publish (Release)

on:
  workflow_run:
    workflows: ["CI"]
    branches:
      - "main"
      - "next"
      - "version/**"
    types: 
      - completed

    
jobs:
  publish-release:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3
      # Setup .npmrc file to publish to GitHub Packages
      - uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          registry-url: 'https://npm.pkg.github.com'
          # Defaults to the user or organization that owns the workflow file
          scope: '@pavelkeyzik'
      - run: npm ci
      - run: echo "🚀 Ship Release"